spring:
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jobexam
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
server:
  storage: D:\storage
  servlet:
    context-path: /jobexam
  dog-api-path: https://dog.ceo/api
logging:
  level:
    root: INFO
    isida:
      by:
        jobexam: INFO